import type { ProviderName } from "../types";

export async function recordProviderSuccess(db: D1Database, provider: ProviderName, at: string, count: number): Promise<void> { await db.prepare(`INSERT INTO provider_source_health (provider, last_success_at, consecutive_failures, last_received_count, updated_at) VALUES (?, ?, 0, ?, ?)
  ON CONFLICT(provider) DO UPDATE SET last_success_at=excluded.last_success_at, consecutive_failures=0, last_error=NULL, last_received_count=excluded.last_received_count, updated_at=excluded.updated_at`).bind(provider, at, count, at).run(); }
export async function recordProviderFailure(db: D1Database, provider: ProviderName, at: string, error: string, count?: number): Promise<void> { await db.prepare(`INSERT INTO provider_source_health (provider, last_failure_at, consecutive_failures, last_error, last_received_count, updated_at) VALUES (?, ?, 1, ?, ?, ?)
  ON CONFLICT(provider) DO UPDATE SET last_failure_at=excluded.last_failure_at, consecutive_failures=provider_source_health.consecutive_failures+1, last_error=excluded.last_error, last_received_count=COALESCE(excluded.last_received_count, provider_source_health.last_received_count), updated_at=excluded.updated_at`).bind(provider, at, error.slice(0, 500), count ?? null, at).run(); }
export async function listProviderHealth(db: D1Database): Promise<Record<string, unknown>[]> { const result = await db.prepare("SELECT provider, last_success_at AS lastSuccessAt, last_failure_at AS lastFailureAt, consecutive_failures AS consecutiveFailures, last_error AS lastError, last_received_count AS lastEventCount, updated_at AS updatedAt FROM provider_source_health ORDER BY provider").all<Record<string, unknown>>(); return result.results; }
export async function failingProviders(db: D1Database): Promise<Record<string, unknown>[]> { const result = await db.prepare("SELECT provider, consecutive_failures AS consecutiveFailures, last_error AS lastError FROM provider_source_health WHERE consecutive_failures >= 3").all<Record<string, unknown>>(); return result.results; }
export async function providersNeedingAlert(db: D1Database, now: string): Promise<Record<string, unknown>[]> { const threshold = new Date(new Date(now).getTime() - 24 * 60 * 60_000).toISOString(); const result = await db.prepare("SELECT provider, consecutive_failures AS consecutiveFailures, last_error AS lastError FROM provider_source_health WHERE consecutive_failures >= 3 AND (last_alert_at IS NULL OR last_alert_at < ?)").bind(threshold).all<Record<string, unknown>>(); return result.results; }
export async function markAlertSent(db: D1Database, provider: string, now: string): Promise<void> { await db.prepare("UPDATE provider_source_health SET last_alert_at=?, updated_at=? WHERE provider=?").bind(now, now, provider).run(); }
